# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpad', '0004_remove_webpad_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpad',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
